# Generated by Django 2.2.14 on 2022-11-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='dummy',
        ),
    ]
